first_mvt/first_mvt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('family/', include('family.urls')),
    path('adventures/', include('adventures.urls')),
    path('possessions/', include('possessions.urls')),
]

first_mvt/home/urls.py
from django.urls import path

from home import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search-members'),
]

first_mvt/possessions/urls.py
from django.urls import path

from possessions import views

app_name = 'possessions'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.possesions_add, name='possesions-add'),
]

first_mvt/possessions/models.py
from django.db import models

# Create your models here.


class Possession(models.Model):
    item = models.CharField(max_length=40)
    value = models.IntegerField()
    owner = models.CharField(max_length=40)

    def __str__(self) -> str:
        return f'Bien {self.item} vale {self.value} y es de {self.owner}'

first_mvt/possessions/forms.py
from django import forms

class PossessionForm(forms.Form):
    item = forms.CharField(
        max_length=40,
        label='Ingrese Item',
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ingrese item',
                'required': True,
            }
        ),
    )
    value = forms.IntegerField(
        label='Ingrese valor',
        required=False,
        widget=forms.NumberInput(
            attrs={
                'required': True,
            }
        ),
    )
    owner = forms.CharField(
        max_length=40,
        label='Ingrese dueño/a',
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ingrese dueño/a',
                'required': True,
            }
        ),
    )

first_mvt/possessions/views.py
from django.shortcuts import render
from django.contrib import messages

from possessions.models import Possession
from possessions.forms import PossessionForm

# Create your views here.

def get_possessions(request):
    return Possession.objects.all()

def index(request):

    posessions = Possession.objects.all()
    context_dict = {
        'possessions': posessions,
    }

    return render(
        request=request,
        context=context_dict,
        template_name='possessions/list_possessions.html'
    )

def possesions_add(request):

    if request.method == 'POST': # Si se envia el formulario, el metodo es post
        possessions_form = PossessionForm(request.POST) # Obtenemos el formulario, y sus datos
        if possessions_form.is_valid(): # Si el formulario es válido (sin errores)
            data = possessions_form.cleaned_data # Entonces borramos el HTML y nos quedamos con los datos puros Key-Values
            actual_objects = Possession.objects.filter(
                item=data['item'],
            ).count() # Creamos una variable que busca en la base de datos si ya existe un item con la misma descripción
            if actual_objects: # Si ya existe, entonces no se puede crear otro igual
                print("Ya existe este objeto")
                messages.error(request, f"Ya existe algun objeto '{data['item']}', vuelve a intentarlo.",)
            else: # De lo contrario, creamos una nueva instancia de clase, guardando los datos el formulario e insertandolós en la base de datos
                new_possession = Possession(
                    item=data['item'],
                    value=data['value'],
                    owner=data['owner'],
                )
                new_possession.save()
                print("Creado con exito")
                messages.success(request, f"Has creado el bien: '{data['item']}' con valor {data['value']} y es de {data['owner']}",)

            return render(
                request=request,
                context={
                    'possessions': get_possessions(request),
                },
                template_name='possessions/list_possessions.html',
                
            )
    
    possessions_form = PossessionForm(request.POST)
    print(possessions_form)
    context_dict = {
        'form': possessions_form,
    }

    return render(
        request=request,
        context=context_dict,
        template_name='possessions/form_possessions.html',
    )

first_mvt/possessions/templates/possessions/form_possessions.html
{% extends 'home/index.html' %}
{% load static %}

{% block title %}
Lista de posesiones de los miembros de la familia
{% endblock %}

{% block content_header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('https://cdn.pixabay.com/photo/2016/10/09/19/19/coins-1726618_960_720.jpg')"> 
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Agregar</h1>
                            <span class="subheading">Posesiones de la familia</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}

{% block content_main %}
        <!-- Form add family possessions -->
        <div>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary" value="Crear posesion" />
            </form>
        </div>
{% endblock %}

first_mvt/possessions/templates/possessions/list_possessions.html
{% extends 'home/index.html' %}
{% load static %}

{% block title %}
Lista de posesiones de los miembros de la familia
{% endblock %}

{% block content_header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('https://cdn.pixabay.com/photo/2016/10/09/19/19/coins-1726618_960_720.jpg')"> 
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Lista</h1>
                            <span class="subheading">Posesiones de la familia</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}

{% block content_main %}
        <!-- Button to add family possession -->
        {% if message %}
        <div>{{ message }}</div>
        {% endif %}
        <center><a href="{% url 'possessions:possesions-add' %}" class="btn btn-primary">Agregar posesion familiar</a></center>
        <hr>
        <!-- List family possessions-->
        <ul>
            {% for possession in possessions %}
            <li>
                Descripción: {{possession.item}} | Valor: ${{possession.value}} | Dueño: {{possession.owner}}
            </li>
            {% endfor %}
        </ul>
{% endblock %}