first_mvt/family/urls.py
from django.urls import path

from family import views

app_name = 'family'
urlpatterns = [
    path('family_members', views.family_list, name='family-list'),
    path('family_members/add', views.family_add_member, name='family-add-member'),
]

first_mvt/first_mvt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('family/', include('family.urls')),
    path('adventures/', include('adventures.urls')),
    path('possessions/', include('possessions.urls')),
]

first_mvt/home/urls.py
from django.urls import path

from home import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search-members'),
]

first_mvt/family/models.py
from django.db import models

# Create your models here.

class Family_member(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    age = models.IntegerField()
    relationship = models.CharField(max_length=40)

    def __str__(self):
        return f'Nombre: {self.name} | Apellido: {self.last_name} | Edad: {self.age} | Relación: {self.relationship}'

first_mvt/family/forms.py
from django import forms

class FamilyMemberForm(forms.Form):
    name = forms.CharField(
        label='Nombre: ',
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Nombre',
                'required': 'True',
            }
        ),
    )
    last_name = forms.CharField(
        label='Apellido: ',
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Apellido',
                'required': 'True',
            }
        ),
    )
    age = forms.IntegerField(
        label='Edad: ',
        required=False,
        widget=forms.NumberInput(
            attrs={
                'placeholder': 'Edad',
                'required': 'True',
            }
        ),
    )
    relationship = forms.CharField(
        label='Relación: ',
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Relación',
                'required': 'True',
            }
        ),
    )

first_mvt/family/views.py
from traceback import print_tb
from django.contrib import messages
from django.shortcuts import render

from family.models import Family_member
from family.forms import FamilyMemberForm

# Create your views here.

def get_members(request):
    members = Family_member.objects.all()
    return members

def family_list(request):
    members = get_members(request)
    context_dict = {'members': members}

    return render(
        request=request,
        context=context_dict,
        template_name='family/member_list.html',
    )

def family_add_member(request):
    if request.method == "POST": # Si el método es POST, entonces:

        member_form = FamilyMemberForm(request.POST)
        '''Primero guardamos en una variable los datos introducidos en el formulario.
        La variable guarda un objeto de tipo FamilyMemberForm, creado en forms.py'''

        if member_form.is_valid(): # Valida si el formato guardado en la variable es correcto
            data = member_form.cleaned_data # Elimina HTML, y deja solo un diccionario con Keys-Values
            actual_objects = Family_member.objects.filter(
                name=data['name'],
                last_name=data['last_name'],
            ).count()
            '''Acá contamos cuantos objetos tienen el nombre y apellido
            que el usuario introdujo en el formulario'''
            if actual_objects:
                '''Verificamos que no exista ningun familiar con este nombre y apellido
                Si existe alguno, se envia un mensaje de error.'''
                messages.error(
                    request,
                    f"El familiar {data['name']} {data['last_name']} ya está creado.",
                )
            else:
                '''Si no existe, se crea un nuevo miembro, con la clase Family_member
                anteriormente definida en los modelos'''
                member = Family_member(
                    name=data['name'],
                    last_name=data['last_name'],
                    age=data['age'],
                    relationship=data['relationship'],
                )
                member.save() # Guardamos en la base de datos
                
                # Enviamos mensaje de miembro creado al usuario
                messages.success(
                    request,
                    f"Has creado a tu {data['relationship']}, {data['name']} {data['last_name']} con {data['age']} años"
                )

            return render(
                request=request,
                context={'members': get_members(request)},
                template_name='family/member_list.html',
            )

    # Si no es POST, entonces:
    member_form = FamilyMemberForm(request.POST)
    context_dict = {'form': member_form}
    return render(
        request=request,
        context=context_dict,
        template_name='family/member_form.html',
    )

first_mvt/family/templates/family/member_form.html
{% extends "home/index.html" %}
{% load static %}

{% block page_title %}
Crear miembro de la familia
{% endblock %}

{% block content_header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('https://cdn.pixabay.com/photo/2015/03/02/23/40/father-656734_960_720.jpg')"> 
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Formulario</h1>
                            <span class="subheading">Crear un miembro de la familia</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}

{% block content_main %}
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Crear miembro" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

first_mvt/family/templates/family/member_list.html
{% extends 'home/index.html' %}
{% load static %}

{% block title %}
Lista de miembros de la familia
{% endblock %}

{% block content_header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('../../static/home/assets/img/home-bg.jpg')"> 
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Lista</h1>
                            <span class="subheading">Miembros de la familia</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}

{% block content_main %}
        <!-- Add family member button -->
        <center><a class="btn btn-primary" href="{% url 'family:family-add-member' %}">Crear miembro de la familia</a></center>
        <hr>
        <!-- List family members-->
        <ul>
            {% for member in members %}
            <li>
                {{member}}
            </li>
            {% endfor %}
        </ul>
{% endblock %}