first_mvt/adventures/urls.py
from django.urls import path

from adventures import views

app_name = 'adventures'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.adventures_add, name='adventures-add'),
]

first_mvt/family/urls.py
from django.urls import path

from family import views

app_name = 'family'
urlpatterns = [
    path('family_members', views.family_list, name='family-list'),
    path('family_members/add', views.family_add_member, name='family-add-member'),
]

first_mvt/first_mvt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('family/', include('family.urls')),
    path('adventures/', include('adventures.urls')),
    path('possessions/', include('possessions.urls')),
]

first_mvt/home/urls.py
from django.urls import path

from home import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search-members'),
]

first_mvt/possessions/urls.py
from django.urls import path

from possessions import views

app_name = 'possessions'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.possesions_add, name='possesions-add'),
]

first_mvt/home/models.py
from django.db import models

# Create your models here.

first_mvt/home/views.py
from django.db.models import Q
from django.contrib import messages
from django.shortcuts import render

from family.models import Family_member


# Create your views here.

def index(request):
    return render(
        request=request,
        context={},
        template_name="home/index.html",
    )

def search(request):
    search_param = request.GET['search_param']
    context_dict = dict()

    if search_param:
        query = Q(name__contains=search_param)
        print(query)
        query.add(Q(relationship__contains=search_param), Q.OR)
        print(query)
        query.add(Q(last_name__contains=search_param), Q.OR)
        print(query)
        members = Family_member.objects.filter(query)
        context_dict.update(
            {
                'members': members,
                'search_param': search_param,
            }
        )

    return render(
        request=request,
        context=context_dict,
        template_name='home/index.html'
    )

first_mvt/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block page_title %}
            Home
            {% endblock %}
        </title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home:index' %}">Blog de la familia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'family:family-list' %}">Miembros</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'possessions:index' %}">Posesiones</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'adventures:index' %}">Aventuras</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content_header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('../../static/home/assets/img/about-bg.jpg')"> 
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Blog proyecto</h1>
                            <span class="subheading">Creado para realizar aprendizaje</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% block content_main %}
                        <h1>Buscar un familiar</h1>
                        <div>
                            <form action="{% url 'home:search-members' %}" method="GET">
                                <input type="text" name="search_param" id="member_name_or_relationship" placeholder="Buscar..." {% if search_param %} value="{{ search_param }}" {% endif %}>
                                <br>
                                <input type="submit" class="btn btn-primary" value="Buscar...">
                                <a style="color: black" href="{% url 'home:index' %}"><i class="fa fa-undo"></i></a>
                            </form>
                        </div>
                        <!-- Luego de buscar, si existe algún resultado, imprimirlo acá -->
                        <dir>
                            {% if members %}
                            <h2>Resultados</h2>
                                {% for member in members %}
                                <p>Encontramos a {{member.name}} {{member.last_name}}, que es tu {{member.relationship}}</p>
                                <hr>
                                {% endfor %}
                            {% endif %}
                        </dir>
                    {% endblock %}
                </div>
            </div>
        </div> 
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>