first_mvt/adventures/urls.py
from django.urls import path

from adventures import views

app_name = 'adventures'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.adventures_add, name='adventures-add'),
]

first_mvt/first_mvt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('family/', include('family.urls')),
    path('adventures/', include('adventures.urls')),
    path('possessions/', include('possessions.urls')),
]

first_mvt/home/urls.py
from django.urls import path

from home import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search-members'),
]

first_mvt/adventures/models.py
from django.db import models
# from ckeditor.fields import RichTextField

# Create your models here.

class Adventure(models.Model):
    place = models.CharField(max_length=40)
    date = models.TextField()
    description = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'Fecha {self.date} | Lugar {self.place}'

first_mvt/adventures/forms.py
from django import forms
# from ckeditor.widgets import CKEditorWidget
from adventures.models import Adventure

class AdventuresForm(forms.Form):
    place = forms.CharField(
        max_length=40,
        label='Lugar:',
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ingrese lugar',
                'required': "True",
            }
        ),
    )
    date = forms.CharField(
        label="Fecha",
        required=False,
        widget=forms.TextInput(
            attrs={
                'required': "True",
            }
        ),
    )
    description = forms.CharField(
        label="Descripción: ",
        required=False,
        widget=forms.TextInput(
            attrs={
                "required": "True",
                'placeholder': 'Detalles de la aventura',
            }
        ),
    )

    class Meta:
        model = Adventure
        fields = ['place', 'date', 'description']

first_mvt/adventures/views.py
from django.shortcuts import render
from adventures.models import Adventure
from adventures.forms import AdventuresForm
# from django.contrib import messages

# Create your views here.

def get_adventures(request):
    adventure = Adventure.objects.all()
    return adventure

def index(request):

    adventures = Adventure.objects.all()
    context_dict = {
        'adventures': adventures,
    }

    return render(
        request=request,
        context=context_dict,
        template_name='adventures/list_adventures.html'
    )

def adventures_add(request):

    if request.method == 'POST':
        adventures_form = AdventuresForm(request.POST)
        if adventures_form.is_valid():
            data = adventures_form.cleaned_data
            print(data)
            actual_objects = Adventure.objects.filter(
                place=data['place'], date=data['date'],
            ).count()
            print(actual_objects)
            if actual_objects:
                print("Error, ya existe")
                #messages.error(
                #    request,
                #    f'Este evento ya existe, intenta con otro',
                #)
            else:
                new_adventure = Adventure(
                    place=data['place'],
                    date=data['date'],
                    description=data['description'],
                )
                new_adventure.save()

            return render(
                request=request,
                context={'adventures': get_adventures(request)},
                template_name='adventures/list_adventures.html',
            )

                # messages.success(
                #     request,
                #     f"¡Felicidades, tienen una nueva aventura!",
                # )


    adventures_form = AdventuresForm(request.POST)
    context_dict = {
        'form': adventures_form,
    }

    return render(
        request=request,
        context=context_dict,
        template_name='adventures/form_adventures.html'
    )

first_mvt/adventures/templates/adventures/form_adventures.html
{% extends 'home/index.html' %}
{% load static %}

<!-- ckeditor-->
<!-- {% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %} -->
<!-- ckeditor-->

{% block title %}
Lista de posesiones de los miembros de la familia
{% endblock %}

{% block content_header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('https://cdn.pixabay.com/photo/2016/10/09/19/19/coins-1726618_960_720.jpg')"> 
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Agregar</h1>
                            <span class="subheading">Aventuras de la familia</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}

{% block content_main %}
        <!-- Form add family possessions -->
        <div>
            <form action="" method="POST">
                {% csrf_token %}
                <!-- {{ form.media }} --> <!-- ckeditor-->
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary" value="Crear aventura" />
            </form>
        </div>
{% endblock %}

first_mvt/adventures/templates/adventures/list_adventures.html
{% extends 'home/index.html' %}
{% load static %}

{% block title %}
Aventuras de la familia
{% endblock %}

{% block content_header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('https://cdn.pixabay.com/photo/2016/02/07/19/48/aurora-1185464_960_720.jpg')"> 
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Lista</h1>
                            <span class="subheading">Aventuras de la familia</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}

{% block content_main %}
        <!-- Add new adventure -->
        <div>
            <center>
                <a href="{% url 'adventures:adventures-add' %}" class="btn btn-primary">Crear nueva aventura</a>
            </center>
            <hr>
        </div>
        <!-- List family adventures-->
        <ul>
            {% for adventure in adventures %}
            <li>
                {{adventure}}
            </li>
            {% endfor %}
        </ul>
{% endblock %}